# Generated by Django 2.0.2 on 2018-04-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20180406_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='saving_list',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
