# Generated by Django 2.0.2 on 2018-04-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_list_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='saving_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
